### ISSUE TITLE
Heavy CPU loading and termination in moose V3.0

### ISSUE THREAD

**Issue by alfab8ta** [ENHANCE-PET/MOOSE#152] opened 2024-10-14 20:01 UTC
I've been testing version 3.0 for a few days now, and I'm quite satisfied with the significantly improved processing speed compared to v2. However, when running certain modules, the system tends to overheat and the program suddenly terminates, likely due to increased CPU load, which was never an issue with v2. 

I’m processing around 4,000 CT scans, and while the "body_composition" prediction runs smoothly and completes in one go, the "clin_ct_organs" module crashes after processing just a few hundred scans. In the resource monitor, CPU peaks are densely packed in v3, while they are relatively loose in v2, which I think accounts for difference in speed.

The main reason I switched to v3 is its larger training dataset, but the issues mentioned above make it difficult to fully benefit from the improved speed. Any comments or advice on resolving this would be greatly appreciated. Alternatively, is there a way to use the new prediction models with v2?

Thanks!

*System
Windows 11 /  14900K / 128GB RAM / RTX 4090 / SSD

**Comment by LalithShiyam** [comment] 2024-10-14 21:51
@Keyn34

**Comment by alfab8ta** [comment] 2024-10-14 21:54
For now, I keep program running by refraining max CPU process status to 97% in power plan option.

**Comment by LalithShiyam** [comment] 2024-10-14 22:00
Hi there, many thanks for notifying this. Frankly, we haven’t seen this so far. I mean we haven’t run 4k cases. Our largest run was 1.2k. But we do quite a bit of repeated runs on this large sample and we had no issues. Since we can't reproduce this, It’s hard for me to tell why this happens. I have copied in @Keyn34 as he is the main guy for this version.

I just spoke to @Keyn34 and he pointed out to the heating issues that are notoriously prevalent in 14900k. This could be an issue. We adopted `dask` to enable out of core computing, which relieves memory and pushes the cores to the limit. Therefore, you get speed and as well as efficiency.

**Comment by LalithShiyam** [comment] 2024-10-14 22:02
> For now, I keep program running by refraining max CPU process status to 97% in power plan option.

And does this help now? To avoid crashes? 

How's the CPU temperature BTW?

**Comment by Keyn34** [comment] 2024-10-14 22:15
Hi @alfab8ta, I'm glad you like it so far. I'm sorry you ran into these troubles. Since you provided your system spec (thanks for that!), I assume that your problems are related to the CPU you are using. As @LalithShiyam mentioned, 13th—and 14th-generation Intel processors are notorious [overheaters](https://community.intel.com/t5/Processors/July-2024-Update-on-Instability-Reports-on-Intel-Core-13th-and/m-p/1617113#M74792). 

You could try confirming this by using a different system (if available) with a different CPU.

> For now, I keep program running by refraining max CPU process status to 97% in power plan option.

Do you notice performance differences? If we see this more often, we might need a safeguard for the 13th and 14th generations.

**Comment by alfab8ta** [comment] 2024-10-14 23:11
Thanks, @Keyn34 and @LalithShiyam. 

I agree that my issue is mainly due to the 14th gen CPU, and I overworked my system too much at a time. The CPU temperature peaks at 100 degrees at full loading, stays around 85% under thermal throttling, and went down to 56 degrees. I haven't tried many options, but refining the max power to 95% significantly decreased the max temperature of the CPU with doubled processing time. However, 96% to 99% didn't seem to make much difference. Anyway, I restored the power option to default because the modification didn't seem to be very effective, and the MOOSE has been fine for an hour so far. Probably giving it some break time would be the best solution. 

Best,

**Comment by LalithShiyam** [comment] 2024-10-15 08:22
Do keep us posted. And considering this is a cpu issue, may I close this issue? As we can't do much about it?

**Comment by alfab8ta** [comment] 2024-10-15 08:49
> Do keep us posted. And considering this is a cpu issue, may I close this issue? As we can't do much about it?

Will do. And, plsease close this issue.

**Closed** 2024-10-15 08:56 UTC

**Comment by LalithShiyam** [comment] 2024-10-16 21:43
Hi there @alfab8ta are you content with the segmentations so far?

**Comment by Keyn34** [comment] 2024-10-17 13:34
Thank you, @alfab8ta, I am looking forward to your insights.

**Comment by LalithShiyam** [comment] 2024-10-17 13:37
@alfab8ta fantastic, I am curious about the accuracy of the actual results.
